---

- hosts: aws
  connection: local
  roles:
    - common
    - sentry
  gather_facts: false
  # Because Ubuntu doesn't come with correct version of Python
  pre_tasks:
    - name: Update apt packages
      raw: apt-get update
    - name: Install python
      raw: apt-get install python3 aptitude -y
    - name: Gather facts
      action: setup
  become: yes

- hosts: dev
  roles:
    - common
    - redis
    - postgres
    - sentry
  gather_facts: false
  # Because Ubuntu doesn't come with correct version of Python
  pre_tasks:
    - name: Update apt packages
      raw: apt-get update
    - name: Install python
      raw: apt-get install python3 aptitude -y
    - name: Gather facts
      action: setup
  become: yes # become sudo
